{% set name = "dask-glm" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dask-glm-{{ version }}.tar.gz
  sha256: 75d698341525bec333ae4bbb7caae5a334668ec8556d0f72ad82256910500a9e

build:
  number: 0
  script: pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - python
    - setuptools
    - setuptools_scm
    - pip
    - wheel
  run:
    - python
    - cloudpickle >=0.2.2
    - dask-core
    - multipledispatch >=0.4.9
    - scipy >=0.18.1
    - scikit-learn >=0.18
    - distributed
    - sparse >=0.7.0

test:
  imports:
    - dask_glm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dask/dask-glm
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Generalized Linear Models in Dask'
  description: |
      Generalized Linear Models for parallel and
      distributed machine learning, built using dask.
  doc_url: https://dask-glm.readthedocs.io
  dev_url: https://github.com/dask/dask-glm

extra:
  recipe-maintainers:
    - TomAugspurger
    - cicdw
