{% set name = "dask-glm" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dask/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: b2fda4fd306c36b1f056a96faec1471f256d3092fa6fed6460acfc2e3b04688f

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<310]

requirements:
  host:
    - python
    - pip
    - setuptools >=61
    - setuptools_scm
  run:
    - python
    - cloudpickle >=1.0
    - dask >=2022.1.0
    - distributed >=2022.1.0
    - multipledispatch >=0.6.0
    - numba >=0.59
    # Pin numpy from dask[array] instead
    # - numpy >=1.21
    # dask[array]
    - numpy >=1.24
    - scipy >=1.7
    - scikit-learn >=1.0
    - sparse >=0.15

test:
  source_files:
    - dask_glm/tests
  imports:
    - dask_glm
    - dask_glm.estimators
  requires:
    - pip
    - pytest >=7.0
    - pytest-xdist >=3.0
  commands:
    - pip check
    - pytest -v dask_glm/tests

about:
  home: https://github.com/dask/dask-glm
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Generalized Linear Models in Dask
  description: |
    Generalized Linear Models for parallel and
    distributed machine learning, built using dask.
  doc_url: https://dask-glm.readthedocs.io
  dev_url: https://github.com/dask/dask-glm

extra:
  recipe-maintainers:
    - TomAugspurger
    - cicdw
