travis:
  secure:
    BINSTAR_TOKEN: CtYSwZQzRiGT1COZnw+i2XVC4nGq5xVsCKAR2B9rhnd2pStF/9N38GvEZeLRel/080GTGjN5T0aPJ7oj0RSSZ9AkY0Rk+HuAgDLRE7WZMtt6+Z4+f5RuzPwGBUICYyMvRJG+YqAQbxKrZ5FGobKrjZF9glfih+FqY0ewR/jSQdKGZKIRUs/wl4NBCoiqau27C7s7MxD0iVFCxbbQKx8F/mTOjRBnRrmftB/9N9EnZquCJJDWST4kF3jJXF0KYiE84RTx4EkMV18f5UMO/h4WesJMXkn39S7tkza/r8D2Hz26WhWiFg9ttnk9e54vznykJUpsWqZ6+27aKdLOpH0fiP1gP8408BLRkAwq3PBJK0b9gv9NX6j067A/+K/ODgFOQIXExa/Eyy+Zdx8qi7zolzCHjLAT0SP0L84tNrYyJ0x4jik7jaJtVaV772+TnLL4S+GcCfI+kZjY8C5hthVkfjbE3Zc3TwU/Y4U/JttG/WF8L5RVkuM2PncnM+CbxNrP/+rTnOg5M+29zNJnGL32804l25sffgttqTKcGyWtHfntfIEgGmIo0fNwOGEk25PKJ1+gF7HIwGbh9F12qq0oUf4YG+i0UhCXY8V8WeWKse47ePG9MPhwyrbqfYm1KOs3PL+nX/tTGpPqRESy43BJASOsUuu3aSEYcET+xCkPxpI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
