travis:
  secure:
    BINSTAR_TOKEN: C0KQvuAMgN2mD9jc3pAkOheuOSGr/yQUW87qdRr4hwADq19SrpDEx266+L0ej6aZ1HfRM/9pEeZoGvrF2wG+qpS+KOKwiN0mDyXOhaE6L4BkKOyV1kIr2bGyisWrWtca1w349Aq9W1QxAVv//L3V0dbUq9xGAWfAj/lrlKhnW/sJS0lNNsnZXC0Lt+3hG4m/X4Imyuxs8NRjV3koieO5FOr7rcFq7boyZlW4F7cM3/zilUxrMfS3C1HfVJezRpAQPwWDFlEAMbE00vS81SkVo7A7gTEB74BhznWG3MXPf/FJqV83yZIXPKxUvGj7I2/1EPGAWju4ObsOEF1/dPoTBxZbyxunDnsOAzywHfg+kUVk2qNczMpfoR1S09YQ7fkxU7MwsK6J60tfxvqFWlXdY6LHxeP0o7DqpYpkQ0cJD4VqxvSxXFNmHxpT9E5ivQlAdRrPjZiS6yd4yT+XWikJnkr+jI+Dg9OjJjhzgS2KGtnl/JVg3vcHvZ6vvCZBZY+xpgitczpnNxHMRVxbMlaqFQfwoXd9Oi4E5aDik1ILXU7QIhFQWpMJKVFYLvzUaEWX948iR4hgW6LJg7V1+OMXg7HRWNMAyjoEz7rvyspAx5E/wEmAaLTO8AJ8g+hwMVnXDs57uBUSxO7AQDrvnBGZxNgISUw4CqD1mhBiAdpDang=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
